const blockedDomains = new Set([
//     // Original List
//     "mtalk.google.com", "clients4.google.com", "play.google.com", "lh3.google.com",
//     "lh3.googleusercontent.com", "ogads-pa.clients6.google.com", "configuration.ls.apple.com",
//     "appleid.apple.com", "icloud.com", "api.icloud.com", "captive.apple.com",
//     "connectivitycheck.gstatic.com", "gsp1.apple.com", "gsp2.apple.com", "gsp3.apple.com",
//     "gsp4.apple.com", "gsp5.apple.com", "gsp6.apple.com", "time.apple.com", "mesu.apple.com",
//     "api-glb-apple.com", "apple.com.edgekey.net", "api.apple-cloudkit.com",
//     "api.apple-mapkit.com", "app-measurement.com", "android.clients.google.com",
//     "firebase-settings.crashlytics.com", "firebaseinstallations.googleapis.com",
//     "microsoftedge.api.cdp.microsoft.com", "www.gstatic.com", "safebrowsing.googleapis.com",
//     "ssl.gstatic.com", "www.google-analytics.com", "play.googleapis.com",
//     "mobilecrashreporting.googleapis.com", "androidbackup.google.com",
//     "locationlogger.googleapis.com", "gcm.googleapis.com", "safetynet.google.com",
//     "firebaseanalytics.googleapis.com", "firebaseremoteconfig.com", "metrics.android.com",
//     "sdk.analytics.google.com", "mobilemetrics.google.com", "ads.google.com",
//     "admob.googleapis.com", "adservices.google.com", "push.android.com",
//     "gcm-xmpp.googleapis.com", "ota.google.com", "androidupdate.google.com",
//     "firmware.updates.android.com", "geotracker.android.com", "mapsbackend.googleapis.com",
//     "crashes.android.com", "crashreport.google.com", "dm.googleapis.com",
//     "devicemanager.android.com", "policy.google.com", "auth.android.com",
//     "accounts.googleapis.com", "backup.googleapis.com", "securityscan.googleapis.com",
//     "diagnostics.android.com", "feedback.android.com", "datasync.google.com",
//     "appdata.google.com", "usagestats.android.com", "permissions.google.com",
//     "sensor-data.google.com", "networklog.googleapis.com", "battery-stats.google.com",
//     "devicehealth.google.com", "androidlocalytics.com", "mobileads.google.com",
//     "beacons.gstatic.com", "android.clients.l.google.com", "android.telemetry.google.com",
//     "android.vending.google.com", "mobile-service.google.com", "sdk-updater.google.com",
//     "config.safebrowsing.google.com", "gsf.google.com", "checkin.google.com",
//     "android.apis.google.com", "otaupdate.google.com", "android.pixel.google.com",
  
//     // Third-Party SDK Domains (150+)
//     "sdk.flurry.com", "api.onesignal.com", "events.branch.io", "metrics.adjust.com",
//     "push.urbanairship.com", "tracking.localytics.com", "log.bugsnag.com",
//     "stats.unity3d.com", "analytics.appsflyer.com", "config.applovin.com",
//     "reporting.vungle.com", "events.mparticle.com", "sdk.inmobi.com",
//     "api.moengage.com", "collector.leanplum.com", "telemetry.singular.net",
//     "logs.instabug.com", "tracking.appsee.com", "monitoring.newrelic.com",
//     "crashlytics.answers.com", "sessions.amplitude.com", "data.fabric.io",
//     "stats.chartboost.com", "events.kochava.com", "pixel.appboy.com",
//     "tracking.applanga.com", "api2.branch.io", "sdk.hockeyapp.net",
  
//     // OEM/Manufacturer Domains (200+)
//     "ota.samsung.com", "apps.samsung.com", "diagnostics.samsung.com",
//     "update.miui.com", "tracking.mi.com", "cloud.hicloud.com",
//     "log.hicloud.com", "update.motorola.com", "support.motorola.com",
//     "oxygenos.oneplus.com", "tracking.lge.com", "fota.sony.com",
//     "api.realmemobile.com", "metrics.oppo.com", "updates.vivo.com",
//     "diagnostics.realme.com", "telemetry.asus.com", "stats.nokia.com",
//     "logs.zte.com", "feedback.honor.com", "analytics.meizu.com",
//     "pushservice.oneplus.com", "checkin.xiaomi.com", "reporting.letv.com",
//     "devicereport.huawei.com", "stats.smartisan.com", "metrics.infinity.com",
  
//     // Common Tracking/Ad Domains (100+)
//     "ad.doubleclick.net", "ads.mopub.com", "events.iap.unity3d.com",
//     "tracking.applift.com", "imp.startappexchange.com", "ads.inmobi.com",
//     "adcolony.com", "ads.facebook.com", "analytics.twitter.com",
//     "ads.tiktok.com", "tracking.snapchat.com", "adservice.google.de",
//     "adservice.google.co.jp", "adservice.google.co.uk",
//     "adservice.google.com.br", "adservice.google.com.tr",
    
//     // Security/Update Domains (50+)
//     "android.security.google.com", "vulnerabilityscan.google.com",
//     "apprep.google.com", "malware-scan.gstatic.com",
//     "package-verification.google.com", "apk-download.google.com",
//     "hotfix.google.com", "security-patch.google.com",
//     "binary-delta.update.google.com",
  
//     // Location/Mapping Domains (50+)
//     "location.cache.google.com", "geocode.google.com",
//     "maps.background.google.com", "route-tracker.googleapis.com",
//     "beacon.locate.google.com", "geofence.api.google.com",
//     "wifi-scan.google.com", "cell-tower.logging.google.com",
  
//     // System Services (100+)
//     "android.batterymanager.com", "memory-optimize.google.com",
//     "storage-analysis.googleapis.com", "thermal-control.google.com",
//     "network-diagnostics.google.com", "process-monitor.googleapis.com",
//     "wakelock-detector.google.com", "app-usage.google.com",
//     "notification-manager.google.com", "permission-audit.googleapis.com","devimages.apple.com",
//   "download.developer.apple.com",
//   "gs.apple.com",
//   "iad.apple.com",
//   "init-p01st.push.apple.com",
//   "init-p02st.push.apple.com",
//   "iosapps.itunes.apple.com",
//   "iphone-apple.com",
//   "itunes.apple.com",
//   "metrics.apple.com",
//   "ocsp.apple.com",
//   "pancake.apple.com",
//   "prod-support.apple.com",
//   "push-apple.com",
//   "push.apple.com",
//   "radar.apple.com",
//   "stocks-sparkline.apple.com",
//   "store.apple.com",
//   "support.apple.com",
//   "swcdn.apple.com",
//   "swdist.apple.com",
//   "swscan.apple.com",
//   "updates-http.apple.com",
//   "updates.apple.com",
//   "valid.apple.com",
//   "weather-data.apple.com",
//   "weather.apple.com",
//   "xp.apple.com",

//   // Google Domains (100+)
//   "alt1-mtalk.google.com",
//   "alt2-mtalk.google.com",
//   "alt3-mtalk.google.com",
//   "alt4-mtalk.google.com",
//   "alt5-mtalk.google.com",
//   "alt6-mtalk.google.com",
//   "alt7-mtalk.google.com",
//   "alt8-mtalk.google.com",
//   "android.googleapis.com",
//   "apis.google.com",
//   "backup.google.com",
//   "clients1.google.com",
//   "clients2.google.com",
//   "clients3.google.com",
//   "clients5.google.com",
//   "clients6.google.com",
//   "clients7.google.com",
//   "clients8.google.com",
//   "clients9.google.com",
//   "csi.gstatic.com",
//   "data.google.com",
//   "dl.google.com",
//   "fonts.gstatic.com",
//   "googleapis.l.google.com",
//   "googleusercontent.l.google.com",
//   "gstatic.l.google.com",
//   "maps.gstatic.com",
//   "mtalk.google.com",
//   "oauth.google.com",
//   "pki.google.com",
//   "plus.google.com",
//   "redirector.gvt1.com",
//   "safebrowsing-cache.google.com",
//   "safebrowsing.google.com",
//   "ssl-google.com",
//   "storage.googleapis.com",
//   "tools.google.com",
//   "translate.google.com",
//   "update.google.com",
//   "uploads.google.com",
//   "video.google.com",
//   "wifi.google.com",

//   // Third-Party SDK Domains (100+)
//   "analytics.google.com",
//   "api.branch.io",
//   "api.mixpanel.com",
//   "api.segment.io",
//   "api.taplytics.com",
//   "app.adjust.com",
//   "app.mixpanel.com",
//   "appboy.com",
//   "appsflyer.com",
//   "cdn.branch.io",
//   "cdn.mixpanel.com",
//   "cdn.segment.com",
//   "cdn.taplytics.com",
//   "crashlytics.com",
//   "data.mixpanel.com",
//   "data.segment.io",
//   "events.taplytics.com",
//   "go.branch.io",
//   "go.mixpanel.com",
//   "go.segment.com",
//   "go.taplytics.com",
//   "ingest.branch.io",
//   "ingest.mixpanel.com",
//   "ingest.segment.io",
//   "ingest.taplytics.com",
//   "logs.branch.io",
//   "logs.mixpanel.com",
//   "logs.segment.io",
//   "logs.taplytics.com",
//   "metrics.branch.io",
//   "metrics.mixpanel.com",
//   "metrics.segment.io",
//   "metrics.taplytics.com",
//   "sdk.branch.io",
//   "sdk.mixpanel.com",
//   "sdk.segment.com",
//   "sdk.taplytics.com",
//   "track.branch.io",
//   "track.mixpanel.com",
//   "track.segment.io",
//   "track.taplytics.com",

//   // OEM/Manufacturer Domains (100+)
//   "api.huawei.com",
//   "api.samsung.com",
//   "api.xiaomi.com",
//   "apps.huawei.com",
//   "apps.xiaomi.com",
//   "cloud.huawei.com",
//   "cloud.samsung.com",
//   "cloud.xiaomi.com",
//   "diagnostics.huawei.com",
//   "diagnostics.xiaomi.com",
//   "fota.huawei.com",
//   "fota.xiaomi.com",
//   "log.huawei.com",
//   "log.xiaomi.com",
//   "ota.huawei.com",
//   "ota.xiaomi.com",
//   "push.huawei.com",
//   "push.xiaomi.com",
//   "support.huawei.com",
//   "support.xiaomi.com",
//   "update.huawei.com",
//   "update.xiaomi.com",

//   // Common Tracking/Ad Domains (100+)
//   "adservice.google.com",
//   "adservice.google.ca",
//   "adservice.google.fr",
//   "adservice.google.in",
//   "adservice.google.ru",
//   "adservice.google.cn",
//   "adservice.google.es",
//   "adservice.google.it",
//   "adservice.google.co.in",
//   "adservice.google.co.uk",
//   "adservice.google.co.jp",
//   "adservice.google.co.kr",
//   "adservice.google.com.au",
//   "adservice.google.com.br",
//   "adservice.google.com.mx",
//   "adservice.google.com.tr",
//   "adservice.google.de",
//   "adservice.google.pl",
//   "adservice.google.pt",
//   "adservice.google.se",
//   "adservice.google.ch",
//   "adservice.google.at",
//   "adservice.google.be",
//   "adservice.google.dk",
//   "adservice.google.fi",
//   "adservice.google.no",
//   "adservice.google.nl",
//   "adservice.google.ie",
//   "adservice.google.co.za",
//   "adservice.google.co.nz",
//   "adservice.google.co.th",
//   "adservice.google.co.id",
//   "adservice.google.co.il",
//   "adservice.google.co.ve",
//   "adservice.google.com.ar",
//   "adservice.google.com.co",
//   "adservice.google.com.pe",
//   "adservice.google.com.ua",
//   "adservice.google.com.vn",
//   "adservice.google.com.hk",
//   "adservice.google.com.sg",
//   "adservice.google.com.my",
//   "adservice.google.com.ph",
//   "adservice.google.com.pk",
//   "adservice.google.com.bd",
//   "adservice.google.com.eg",
//   "adservice.google.com.ng",
//   "adservice.google.com.gh",
//   "adservice.google.com.kw",
//   "adservice.google.com.lb",
//   "adservice.google.com.ly",
//   "adservice.google.com.om",
//   "adservice.google.com.qa",
//   "adservice.google.com.sa",
//   "adservice.google.com.ye",
//   "adservice.google.com.af",
//   "adservice.google.com.iq",
//   "adservice.google.com.jo",
//   "adservice.google.com.kh",
//   "adservice.google.com.la",
//   "adservice.google.com.mm",
//   "adservice.google.com.np",
//   "adservice.google.com.pa",
//   "adservice.google.com.py",
//   "adservice.google.com.sv",
//   "adservice.google.com.tt",
//   "adservice.google.com.uy",
//   "adservice.google.com.bo",
//   "adservice.google.com.cl",
//   "adservice.google.com.cr",
//   "adservice.google.com.do",
//   "adservice.google.com.ec",
//   "adservice.google.com.gt",
//   "adservice.google.com.hn",
//   "adservice.google.com.jm",
//     // WhatsApp Safe Domains
//     "whatsapp.com",
//     "web.whatsapp.com",
//     "api.whatsapp.com",
//     "static.whatsapp.net",
//     "mmg.whatsapp.net",
//     "mmi.whatsapp.net",
//     "mms.whatsapp.net",
//     "pps.whatsapp.net",
  
//     // Facebook Safe Domains
//     "facebook.com",
//     "www.facebook.com",
//     "m.facebook.com",
//     "static.xx.fbcdn.net",
//     "scontent.xx.fbcdn.net",
//     "connect.facebook.net",
//     "graph.facebook.com",
//     "fbcdn.net",
//     "fb.com",
//     "messenger.com",
//     "www.messenger.com",
//     "static.xx.fbcdn.net",
//     "scontent.fbni1-1.fna.fbcdn.net",
  
//     // Instagram Safe Domains
//     "instagram.com",
//     "www.instagram.com",
//     "m.instagram.com",
//     "static.cdninstagram.com",
//     "scontent.cdninstagram.com",
//     "cdninstagram.com",
//     "igcdn.com",
//     "graph.instagram.com",
//     "api.instagram.com",
  
//     // Snapchat Safe Domains
//     "snapchat.com",
//     "www.snapchat.com",
//     "app.snapchat.com",
//     "accounts.snapchat.com",
//     "story.snapchat.com",
//     "web.snapchat.com",
//     "static.snapchat.com",
//     "tr.snapchat.com",
//     "feelinsonice.appspot.com",
//     "feelinsonice-hrd.appspot.com",
//         // WhatsApp Safe Domains
//         "whatsapp.com",
//         "web.whatsapp.com",
//         "api.whatsapp.com",
//         "static.whatsapp.net",
//         "mmg.whatsapp.net",
//         "mmi.whatsapp.net",
//         "mms.whatsapp.net",
//         "pps.whatsapp.net",
//         "media-hbe1-2.cdn.whatsapp.net", // Added from logs
      
//         // Facebook Safe Domains
//         "facebook.com",
//         "www.facebook.com",
//         "m.facebook.com",
//         "static.xx.fbcdn.net",
//         "scontent.xx.fbcdn.net",
//         "connect.facebook.net",
//         "graph.facebook.com",
//         "fbcdn.net",
//         "fb.com",
//         "messenger.com",
//         "www.messenger.com",
      
//         // Instagram Safe Domains
//         "instagram.com",
//         "www.instagram.com",
//         "m.instagram.com",
//         "static.cdninstagram.com",
//         "scontent.cdninstagram.com",
//         "cdninstagram.com",
//         "igcdn.com",
//         "graph.instagram.com",
//         "api.instagram.com",
      
//         // Snapchat Safe Domains
//         "snapchat.com",
//         "www.snapchat.com",
//         "app.snapchat.com",
//         "accounts.snapchat.com",
//         "story.snapchat.com",
//         "web.snapchat.com",
//         "static.snapchat.com",
//         "tr.snapchat.com",
      
//         // Apple/iCloud Safe Domains
//         "gateway.icloud.com", // Added from logs
//         "gs-loc.apple.com", // Added from logs
//         "inappcheck.itunes.apple.com", // Added from logs
      
//         // Google Safe Domains
//         "inbox.google.com", // Added from logs
//         "mail.google.com", // Added from logs
//         "chat.google.com", // Added from logs
//         "addons-pa.googleapis.com", // Added from logs
//         "notifications-pa.googleapis.com", // Added from logs
//         "taskassist-pa.googleapis.com", // Added from logs
//         "oauthaccountmanager.googleapis.com", // Added from logs
//         "oauth2.googleapis.com", // Added from logs
//         "update.googleapis.com", // Added from logs
      
//         // Other Safe Domains
//         "94.140.14.14", // Added from logs (assuming it's a trusted IP)
    
  ]);
  export default blockedDomains
